### ISSUE TITLE
import 'vuetify/dist/vuetify.css' is not working

### ISSUE THREAD

**Issue by BennyAlex** [vuetifyjs/webpack#13]
Hello,
I try to configurate my own project since I updated to 0.17.0
importing the css with 
`import 'vuetify/dist/vuetify.css`
or 
`import('path/to/node_modules/vuetify/dist/vuetify.min.css')`
in main.js isn't working.
Only from my main.styl I can import it with `@import '../../node_modules/vuetify/src/stylus/main.styl' `.
Any idea why it isn't working within main.js?

**Comment by nekosaur** [comment]
We need more info than it isn't working.

**Comment by BennyAlex** [comment]
As far as I know, I can remove vuetify-loader with 0.17.0 or?

**Comment by BennyAlex** [comment]
@nekosaur I created the project initially with the webpack-advanced template and now I want to upgrade to 0.17.0

**Comment by nekosaur** [comment]
Yes, remove vuetify-loader. I will be looking over the templates that use it this evening, and document necessary changes
