### ISSUE TITLE
seems like "npm run unit" not working

### ISSUE THREAD

**Issue by mr838wind** [vuetifyjs/webpack#13]
2018.05.17 I check outed webpack sample using all default options.
"vue init vuetifyjs/webpack my-webpack" 

---------------------------------------------------
$ npm run unit

> my-webpack@1.0.0 unit D:\DEV\00_git_sample\my-webpack
> jest --config test/unit/jest.conf.js --coverage

FAIL test\unit\specs\HelloWorld.spec.js
  HelloWorld.vue
    × should render correct contents (17ms)

  ● HelloWorld.vue › should render correct contents

    TypeError: Cannot read property 'textContent' of null

      at Object.<anonymous> (test/unit/specs/HelloWorld.spec.js:8:45)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  console.error node_modules\vue\dist\vue.runtime.common.js:589
    [Vue warn]: Unknown custom element: <v-container> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

    (found in <Root>)

  console.error node_modules\vue\dist\vue.runtime.common.js:589
    [Vue warn]: Unknown custom element: <v-slide-y-transition> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

    (found in <Root>)

  console.error node_modules\vue\dist\vue.runtime.common.js:589
    [Vue warn]: Unknown custom element: <v-layout> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

    (found in <Root>)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.079s
Ran all test suites.
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
 App.vue  |        0 |        0 |        0 |        0 |... 99,100,101,102 |
----------|----------|----------|----------|----------|-------------------|
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-webpack@1.0.0 unit: `jest --config test/unit/jest.conf.js --coverage`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-webpack@1.0.0 unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\windfall\AppData\Roaming\npm-cache\_logs\2018-05-17T06_33_45_506Z-debug.log

**Comment by philippschladitz** [comment]
You can fix it by changing the actual spec. Test something like this: 

```
expect(vm.$el.querySelector('blockquote').textContent)
    .toContain('First, solve the problem. Then, write the code.');
```
