### ISSUE TITLE
Can't init (download) vuetifyjs/webpack

### ISSUE THREAD

**Issue by luke82** [vuetifyjs/webpack#14]
Hello,
I am new in vue/vuetify and I try download vuetifyjs/webpack via CLI.
I used this:

> npm install -g vue-cli
> vue init vuetifyjs/webpack vuetifytest

It start download template and then show this two lines:

> Project name vuetifytest
> Project description (A Vue.js project)

First line I confirm by enter, and then process ends. Thats all. Folder "vuetifytest" is not created.

What is wrong?
Thank you

**Comment by jasoncmcg** [comment]
It may be unrelated, but check this out: https://medium.com/vuetify/how-vue-cli-3-will-shape-our-future-eb7c01f4a241

**Comment by jasoncmcg** [comment]
vue create <project name>
vue add vuetify

**Comment by luke82** [comment]
Thank you for your reply. I got it. Problem was in nodejs version. I installed 10.3.0 insted of recommended 8.11.2 LTS. I uninstall version 10 and install ver. 8. Then all works fine.

**Comment by jasoncmcg** [comment]
Ah, I installed nodist on win and n on lin. A lot of stuff doesn't seem to work right in 10.
