### ISSUE TITLE
import 'vuetify/dist/vuetify.css' is not working

### ISSUE THREAD

**Issue by vibou** [vuetifyjs/webpack#17]
Sorry for the duplicate. 

I have a project created with vue-cli and webpack. I m currently running the version 0.16.9. When I try to upgrade to 0.17.6 The css import in the main is not working anymore although the path seems correct.

There is another issue about this, however I could not figure out what to do to make it works.

Thanks for you help.

**Comment by nekosaur** [comment]
Please post your `webpack.config.js` file

**Comment by vibou** [comment]
Ok you will take me for a noob. I forgot to embed my app inside a <v-app> element.
