### ISSUE TITLE
app.css is loaded at the top of the <head>

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/webpack#17]
It can be an issue when someone uses Material Icons from loaded locally (not from npm)

## Repro:
https://github.com/jacekkarczmarczyk/vuetify-css-loader-bug

## Steps to reproduce:
`yarn build` and look at the generated index.html:

```html
<head>
  <link href=/static/css/app.8acaa58d9550102cf472f59a214ef303.css rel=stylesheet>
</head>
<head>
  <meta charset=utf-8>
  <meta name=viewport content="width=device-width,initial-scale=1">
  <title>style bug</title>
  <link rel=stylesheet type=text/css href=static/fonts/roboto/roboto.css>
  <link rel=stylesheet type=text/css href=static/fonts/material-icons/material-icons.css>
  <link rel=stylesheet type=text/css href=static/fonts/mdi/css/materialdesignicons.css>
```

If you open it in the browser you'll see:
![image](https://user-images.githubusercontent.com/15625235/42596877-6afac22a-8557-11e8-8152-5c5e8a3e8114.png)

That might be a bug in loader itself, but maybe it can be fixed by settings some options

**Comment by jacekkarczmarczyk** [comment]
already fixed

**Comment by KaelWD** [comment]
> nvm fixed it

![image](https://user-images.githubusercontent.com/16421948/42643143-c38493b4-863b-11e8-9db1-93b3561478b9.png)

**Comment by jacekkarczmarczyk** [comment]
missing `</head>`
